version: '3'

services:
  db-svc:
      image: postgres:14.4
      restart: always
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      container_name: db-svc
      environment:
        - POSTGRES_DBNAME=goo
        - POSTGRES_USER=goo
        - POSTGRES_PASSWORD=goo
      ports:
        - 5432:5432
      expose:
        - 5432
  backend-svc:
    image: db-lab-backend
    restart: always
    container_name: backend
    ports:
      - 8080:8080
    expose:
      - 8080
